Added Logo Images to Roses Score
LA1TV/Roses-CasparCG-Graphics pull request #55
Opened 2017-04-21 21:49 UTC by danleedham

[Logos Scores.zip](https://github.com/LA1TV/Roses-CasparCG-Graphics/files/948394/Logos.Scores.zip)

2017-04-21 23:37 UTC, danleedham commented
[New Football Thing.zip](https://github.com/LA1TV/Roses-CasparCG-Graphics/files/948562/New.Football.Thing.zip)

I've also adapted the Roses score with logos to be used as a this match is 'coming up' graphic or as a 'half time/fulltime score' graphic.  Video shows what's going on and the issue with using more than two lines of text as the header.

2017-04-23 14:02 UTC, stephenrob requested changes
All looks fine besides the multi line of text being hidden behind the logo - around 1/2 way through the video you will see what I mean. Probably can fix it with margin or padding.

2017-04-23 14:58 UTC, danleedham commented
I went with a more scientific approach to padding. Before I'd only had 40px for each, but in fact each logo covers the h1 text slightly differently even through the center of each is in the same relative place on each side. 

![screen shot 2017-04-23 at 15 52 50](https://cloud.githubusercontent.com/assets/12582998/25314521/8838a3b6-283d-11e7-89db-12d7aad4339b.png)

2017-04-23 15:18 UTC, tjenkinson commented
That looks snazzy

On 23 Apr 2017, at 16:58, Dan Leedham <notifications@github.com<mailto:notifications@github.com>> wrote:


I went with a more scientific approach to padding. Before I'd only had 40px for each, but in fact each logo covers the h1 text slightly differently even through the center of each is in the same relative place on each side.

[screen shot 2017-04-23 at 15 52 50]<https://cloud.githubusercontent.com/assets/12582998/25314521/8838a3b6-283d-11e7-89db-12d7aad4339b.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://github.com/LA1TV/Roses-CasparCG-Graphics/pull/55#issuecomment-296449089>, or mute the thread<https://github.com/notifications/unsubscribe-auth/ADG-WdQSpfxvENSdEKssTXi3nT_GC8Ssks5ry2b5gaJpZM4NE05O>.

2017-04-25 20:46 UTC, stephenrob approved these changes

2017-04-25 20:46 UTC, merged